### ISSUE TITLE
Publish reports to Kubernetes

### ISSUE THREAD

**Issue by ashwin153** [wager/hub#12]
- https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/
- All CronJob `schedule:` times are based on the timezone of the kube-controller-manager. kubernetes/kubernetes#47202

```yaml
apiVersion: batch/v1
kind: CronJob
metadata: {report.metadata}
spec:
  schedule: {report.schedule}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {report.name}
              image: ???
              imagePullPolicy: IfNotPresent
```
