### ISSUE TITLE
Automatically delete untagged images from Artifact Registry

### ISSUE THREAD

**Issue by ashwin153** [wager/hub#47]
### What would you like to be added?

Automatically delete untagged images from Artifact Registry after pushing images in the CI workflow.

https://misterorion.com/gcloud-delete-untagged-images/

### Why is this needed?

Reduce the size of the Google Cloud bill.

**Comment by ashwin153** [comment]
```bash
repositories = (
  "us-east4-docker.pkg.dev/wager-233003/parlay/"
  "us-east4-docker.pkg.dev/wager-233003/wager/"
)

for repository in "${repositories[@]}"; do
  gcloud artifacts docker images list --quiet --format=json --filter='-tags:*' "${repository}" \
    | jq -r '.[] | (.package + "@" + .version)' \
    | xargs -d '\n' -n 1 -r gcloud artifacts docker images delete --quiet
done
```

**Comment by ashwin153** [comment]
```bash
kubectl get pods --all-namespaces \
  | grep Shutdown \
  | awk '{print $1,$2}' \
  | xargs -n2 bash -c 'kubectl delete pod -n $0 $1'
```

**Comment by ashwin153** [comment]
`kubectl delete pods --field-selector status.phase=Failed -A --ignore-not-found=true`

**Comment by ashwin153** [comment]
Add a GitHub Actions that runs these and other maintenance tasks periodically.

**Comment by ashwin153** [comment]
```
name: maintenance
on:
  schedule:
    - cron: '0 0 * * 0'
jobs:
  artifact-registry:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        repository:
          - us-east4-docker.pkg.dev/wager-233003/parlay/
          - us-east4-docker.pkg.dev/wager-233003/wager/
    steps:
      - name: Prune Images
        run: |-
          gcloud artifacts docker images list --quiet --format=json --filter='-tags:*' ${{ matrix.repository }} \
            | jq -r '.[] | (.package + "@" + .version)' \
            | xargs -d '\n' -n 1 -r gcloud artifacts docker images delete --quiet
  kubernetes:
    runs-on: ubuntu-20.04
    steps:
      - name: Prune Pods
        run: |-
          kubectl delete pods \
            --all-namespaces \
            --field-selector status.phase=Failed \
            --ignore-not-found=true
```
